In [1]:
from Core import *
import matplotlib.pyplot as plt
import cv2
import numpy as np

In [2]:
image = Io().read_image_from_folder()

In [3]:
gray_image = Color(image).bgr_to_gray()

In [4]:
image

array([[[  4,  59,  96],
        [  4,  59,  96],
        [  5,  60,  97],
        ...,
        [119,  82,  86],
        [ 18,   7,  10],
        [ 28,  30,  31]],

       [[  4,  59,  96],
        [  4,  59,  96],
        [  5,  60,  97],
        ...,
        [121,  84,  88],
        [ 23,  10,  12],
        [ 24,  26,  27]],

       [[  4,  59,  96],
        [  4,  59,  96],
        [  5,  60,  97],
        ...,
        [129,  92,  96],
        [ 31,  18,  20],
        [ 19,  19,  19]],

       ...,

       [[ 29, 133,  98],
        [ 29, 133,  98],
        [ 31, 133,  98],
        ...,
        [149, 105,  68],
        [148, 103,  69],
        [146, 102,  65]],

       [[ 30, 132,  97],
        [ 30, 132,  97],
        [ 30, 132,  97],
        ...,
        [148, 106,  71],
        [146, 103,  70],
        [144, 102,  67]],

       [[ 30, 132,  97],
        [ 30, 132,  97],
        [ 30, 132,  97],
        ...,
        [147, 104,  71],
        [145, 102,  69],
        [142,  99,  66]]

In [5]:
print(np.min(image))
print(np.max(image))

0
255


In [6]:
img = image.astype(np.float64)
img

array([[[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [119.,  82.,  86.],
        [ 18.,   7.,  10.],
        [ 28.,  30.,  31.]],

       [[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [121.,  84.,  88.],
        [ 23.,  10.,  12.],
        [ 24.,  26.,  27.]],

       [[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [129.,  92.,  96.],
        [ 31.,  18.,  20.],
        [ 19.,  19.,  19.]],

       ...,

       [[ 29., 133.,  98.],
        [ 29., 133.,  98.],
        [ 31., 133.,  98.],
        ...,
        [149., 105.,  68.],
        [148., 103.,  69.],
        [146., 102.,  65.]],

       [[ 30., 132.,  97.],
        [ 30., 132.,  97.],
        [ 30., 132.,  97.],
        ...,
        [148., 106.,  71.],
        [146., 103.,  70.],
        [144., 102.,  67.]],

       [[ 30., 132.,  97.],
        [ 30., 132.,  97.],
        [ 30., 1

In [7]:
print(np.min(img))
print(np.max(img))

0.0
255.0


In [8]:
im = img / np.max(img)
im

array([[[0.01568627, 0.23137255, 0.37647059],
        [0.01568627, 0.23137255, 0.37647059],
        [0.01960784, 0.23529412, 0.38039216],
        ...,
        [0.46666667, 0.32156863, 0.3372549 ],
        [0.07058824, 0.02745098, 0.03921569],
        [0.10980392, 0.11764706, 0.12156863]],

       [[0.01568627, 0.23137255, 0.37647059],
        [0.01568627, 0.23137255, 0.37647059],
        [0.01960784, 0.23529412, 0.38039216],
        ...,
        [0.4745098 , 0.32941176, 0.34509804],
        [0.09019608, 0.03921569, 0.04705882],
        [0.09411765, 0.10196078, 0.10588235]],

       [[0.01568627, 0.23137255, 0.37647059],
        [0.01568627, 0.23137255, 0.37647059],
        [0.01960784, 0.23529412, 0.38039216],
        ...,
        [0.50588235, 0.36078431, 0.37647059],
        [0.12156863, 0.07058824, 0.07843137],
        [0.0745098 , 0.0745098 , 0.0745098 ]],

       ...,

       [[0.11372549, 0.52156863, 0.38431373],
        [0.11372549, 0.52156863, 0.38431373],
        [0.12156863, 0

In [9]:
print(np.min(im))
print(np.max(im))

0.0
1.0


In [10]:
i = im * 255
i

array([[[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [119.,  82.,  86.],
        [ 18.,   7.,  10.],
        [ 28.,  30.,  31.]],

       [[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [121.,  84.,  88.],
        [ 23.,  10.,  12.],
        [ 24.,  26.,  27.]],

       [[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [129.,  92.,  96.],
        [ 31.,  18.,  20.],
        [ 19.,  19.,  19.]],

       ...,

       [[ 29., 133.,  98.],
        [ 29., 133.,  98.],
        [ 31., 133.,  98.],
        ...,
        [149., 105.,  68.],
        [148., 103.,  69.],
        [146., 102.,  65.]],

       [[ 30., 132.,  97.],
        [ 30., 132.,  97.],
        [ 30., 132.,  97.],
        ...,
        [148., 106.,  71.],
        [146., 103.,  70.],
        [144., 102.,  67.]],

       [[ 30., 132.,  97.],
        [ 30., 132.,  97.],
        [ 30., 1

In [11]:
print(np.min(i))
print(np.max(i))

0.0
255.0


In [14]:
psn = np.random.poisson(image)
psn

array([[[  3,  70, 100],
        [  4,  66, 103],
        [  7,  52,  87],
        ...,
        [113,  73,  78],
        [ 15,  12,   7],
        [ 41,  24,  26]],

       [[  6,  60, 103],
        [  3,  47,  90],
        [  5,  73, 115],
        ...,
        [152,  85,  92],
        [ 24,  14,  10],
        [ 25,  26,  27]],

       [[  3,  57, 112],
        [  6,  80, 103],
        [  2,  55,  94],
        ...,
        [144,  78,  84],
        [ 34,  25,  17],
        [ 23,  27,  28]],

       ...,

       [[ 30, 147,  99],
        [ 34, 132,  92],
        [ 31, 111, 100],
        ...,
        [162, 108,  55],
        [154, 111,  63],
        [151, 109,  67]],

       [[ 33, 158,  93],
        [ 20, 118, 103],
        [ 25, 125,  97],
        ...,
        [136, 104,  83],
        [150,  85,  59],
        [133, 101,  68]],

       [[ 36, 140, 107],
        [ 30, 124, 111],
        [ 23, 124, 120],
        ...,
        [151,  98,  84],
        [146, 100,  67],
        [164, 104,  68]]

In [15]:
print(np.min(psn))
print(np.max(psn))

0
324


In [16]:
ps = psn / np.max(psn)
ps

array([[[0.00925926, 0.21604938, 0.30864198],
        [0.01234568, 0.2037037 , 0.31790123],
        [0.02160494, 0.16049383, 0.26851852],
        ...,
        [0.34876543, 0.22530864, 0.24074074],
        [0.0462963 , 0.03703704, 0.02160494],
        [0.12654321, 0.07407407, 0.08024691]],

       [[0.01851852, 0.18518519, 0.31790123],
        [0.00925926, 0.14506173, 0.27777778],
        [0.0154321 , 0.22530864, 0.35493827],
        ...,
        [0.4691358 , 0.26234568, 0.28395062],
        [0.07407407, 0.04320988, 0.0308642 ],
        [0.07716049, 0.08024691, 0.08333333]],

       [[0.00925926, 0.17592593, 0.34567901],
        [0.01851852, 0.24691358, 0.31790123],
        [0.00617284, 0.16975309, 0.29012346],
        ...,
        [0.44444444, 0.24074074, 0.25925926],
        [0.10493827, 0.07716049, 0.05246914],
        [0.07098765, 0.08333333, 0.08641975]],

       ...,

       [[0.09259259, 0.4537037 , 0.30555556],
        [0.10493827, 0.40740741, 0.28395062],
        [0.09567901, 0

In [17]:
print(np.min(ps))
print(np.max(ps))

0.0
1.0


In [19]:
p = ps * 255
p

array([[[  2.36111111,  55.09259259,  78.7037037 ],
        [  3.14814815,  51.94444444,  81.06481481],
        [  5.50925926,  40.92592593,  68.47222222],
        ...,
        [ 88.93518519,  57.4537037 ,  61.38888889],
        [ 11.80555556,   9.44444444,   5.50925926],
        [ 32.26851852,  18.88888889,  20.46296296]],

       [[  4.72222222,  47.22222222,  81.06481481],
        [  2.36111111,  36.99074074,  70.83333333],
        [  3.93518519,  57.4537037 ,  90.50925926],
        ...,
        [119.62962963,  66.89814815,  72.40740741],
        [ 18.88888889,  11.01851852,   7.87037037],
        [ 19.67592593,  20.46296296,  21.25      ]],

       [[  2.36111111,  44.86111111,  88.14814815],
        [  4.72222222,  62.96296296,  81.06481481],
        [  1.57407407,  43.28703704,  73.98148148],
        ...,
        [113.33333333,  61.38888889,  66.11111111],
        [ 26.75925926,  19.67592593,  13.37962963],
        [ 18.10185185,  21.25      ,  22.03703704]],

       ...,

      

In [20]:
print(np.min(p))
print(np.max(p))

0.0
255.0


In [22]:
p.astype(np.uint8)

array([[[  2,  55,  78],
        [  3,  51,  81],
        [  5,  40,  68],
        ...,
        [ 88,  57,  61],
        [ 11,   9,   5],
        [ 32,  18,  20]],

       [[  4,  47,  81],
        [  2,  36,  70],
        [  3,  57,  90],
        ...,
        [119,  66,  72],
        [ 18,  11,   7],
        [ 19,  20,  21]],

       [[  2,  44,  88],
        [  4,  62,  81],
        [  1,  43,  73],
        ...,
        [113,  61,  66],
        [ 26,  19,  13],
        [ 18,  21,  22]],

       ...,

       [[ 23, 115,  77],
        [ 26, 103,  72],
        [ 24,  87,  78],
        ...,
        [127,  85,  43],
        [121,  87,  49],
        [118,  85,  52]],

       [[ 25, 124,  73],
        [ 15,  92,  81],
        [ 19,  98,  76],
        ...,
        [107,  81,  65],
        [118,  66,  46],
        [104,  79,  53]],

       [[ 28, 110,  84],
        [ 23,  97,  87],
        [ 18,  97,  94],
        ...,
        [118,  77,  66],
        [114,  78,  52],
        [129,  81,  53]]

another way ==============================================================

In [23]:
img1 = image.astype(np.float64)
img1

array([[[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [119.,  82.,  86.],
        [ 18.,   7.,  10.],
        [ 28.,  30.,  31.]],

       [[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [121.,  84.,  88.],
        [ 23.,  10.,  12.],
        [ 24.,  26.,  27.]],

       [[  4.,  59.,  96.],
        [  4.,  59.,  96.],
        [  5.,  60.,  97.],
        ...,
        [129.,  92.,  96.],
        [ 31.,  18.,  20.],
        [ 19.,  19.,  19.]],

       ...,

       [[ 29., 133.,  98.],
        [ 29., 133.,  98.],
        [ 31., 133.,  98.],
        ...,
        [149., 105.,  68.],
        [148., 103.,  69.],
        [146., 102.,  65.]],

       [[ 30., 132.,  97.],
        [ 30., 132.,  97.],
        [ 30., 132.,  97.],
        ...,
        [148., 106.,  71.],
        [146., 103.,  70.],
        [144., 102.,  67.]],

       [[ 30., 132.,  97.],
        [ 30., 132.,  97.],
        [ 30., 1

In [24]:
print(np.min(img1))
print(np.max(img1))

0.0
255.0


In [25]:
psn1 = np.random.poisson(image)
psn1

array([[[  6,  71, 100],
        [  3,  55, 115],
        [  4,  59, 109],
        ...,
        [136,  84,  71],
        [ 15,   3,   7],
        [ 31,  23,  38]],

       [[  4,  47,  94],
        [  5,  56,  91],
        [  9,  53,  95],
        ...,
        [114,  84,  87],
        [ 33,  10,  13],
        [ 29,  31,  20]],

       [[  6,  69, 105],
        [  7,  48,  93],
        [  1,  72, 111],
        ...,
        [131,  71, 104],
        [ 32,  21,  16],
        [ 25,  20,  19]],

       ...,

       [[ 29, 133,  95],
        [ 27, 111,  86],
        [ 27, 127, 109],
        ...,
        [173, 111,  64],
        [155, 113,  65],
        [161, 108,  69]],

       [[ 23, 119,  99],
        [ 18, 135,  91],
        [ 29, 129, 109],
        ...,
        [136, 110,  61],
        [148, 108,  75],
        [171,  85,  66]],

       [[ 30, 153,  79],
        [ 25, 147, 100],
        [ 34, 158,  78],
        ...,
        [155,  85,  76],
        [143,  96,  72],
        [161,  79,  63]]

In [26]:
print(np.min(psn1))
print(np.max(psn1))

0
320


In [27]:
psn11 = psn1.astype(np.float64)
psn11

array([[[  6.,  71., 100.],
        [  3.,  55., 115.],
        [  4.,  59., 109.],
        ...,
        [136.,  84.,  71.],
        [ 15.,   3.,   7.],
        [ 31.,  23.,  38.]],

       [[  4.,  47.,  94.],
        [  5.,  56.,  91.],
        [  9.,  53.,  95.],
        ...,
        [114.,  84.,  87.],
        [ 33.,  10.,  13.],
        [ 29.,  31.,  20.]],

       [[  6.,  69., 105.],
        [  7.,  48.,  93.],
        [  1.,  72., 111.],
        ...,
        [131.,  71., 104.],
        [ 32.,  21.,  16.],
        [ 25.,  20.,  19.]],

       ...,

       [[ 29., 133.,  95.],
        [ 27., 111.,  86.],
        [ 27., 127., 109.],
        ...,
        [173., 111.,  64.],
        [155., 113.,  65.],
        [161., 108.,  69.]],

       [[ 23., 119.,  99.],
        [ 18., 135.,  91.],
        [ 29., 129., 109.],
        ...,
        [136., 110.,  61.],
        [148., 108.,  75.],
        [171.,  85.,  66.]],

       [[ 30., 153.,  79.],
        [ 25., 147., 100.],
        [ 34., 1

In [28]:
print(np.min(psn11))
print(np.max(psn11))

0.0
320.0


In [33]:
ps1 = (psn1 - np.min(psn1)) / (np.max(psn1) - np.min(psn1))
ps1

array([[[0.01875 , 0.221875, 0.3125  ],
        [0.009375, 0.171875, 0.359375],
        [0.0125  , 0.184375, 0.340625],
        ...,
        [0.425   , 0.2625  , 0.221875],
        [0.046875, 0.009375, 0.021875],
        [0.096875, 0.071875, 0.11875 ]],

       [[0.0125  , 0.146875, 0.29375 ],
        [0.015625, 0.175   , 0.284375],
        [0.028125, 0.165625, 0.296875],
        ...,
        [0.35625 , 0.2625  , 0.271875],
        [0.103125, 0.03125 , 0.040625],
        [0.090625, 0.096875, 0.0625  ]],

       [[0.01875 , 0.215625, 0.328125],
        [0.021875, 0.15    , 0.290625],
        [0.003125, 0.225   , 0.346875],
        ...,
        [0.409375, 0.221875, 0.325   ],
        [0.1     , 0.065625, 0.05    ],
        [0.078125, 0.0625  , 0.059375]],

       ...,

       [[0.090625, 0.415625, 0.296875],
        [0.084375, 0.346875, 0.26875 ],
        [0.084375, 0.396875, 0.340625],
        ...,
        [0.540625, 0.346875, 0.2     ],
        [0.484375, 0.353125, 0.203125],
        [

In [34]:
print(np.min(ps1))
print(np.max(ps1))

0.0
1.0


In [35]:
p1 = ps1 * 255.0
p1

array([[[  4.78125 ,  56.578125,  79.6875  ],
        [  2.390625,  43.828125,  91.640625],
        [  3.1875  ,  47.015625,  86.859375],
        ...,
        [108.375   ,  66.9375  ,  56.578125],
        [ 11.953125,   2.390625,   5.578125],
        [ 24.703125,  18.328125,  30.28125 ]],

       [[  3.1875  ,  37.453125,  74.90625 ],
        [  3.984375,  44.625   ,  72.515625],
        [  7.171875,  42.234375,  75.703125],
        ...,
        [ 90.84375 ,  66.9375  ,  69.328125],
        [ 26.296875,   7.96875 ,  10.359375],
        [ 23.109375,  24.703125,  15.9375  ]],

       [[  4.78125 ,  54.984375,  83.671875],
        [  5.578125,  38.25    ,  74.109375],
        [  0.796875,  57.375   ,  88.453125],
        ...,
        [104.390625,  56.578125,  82.875   ],
        [ 25.5     ,  16.734375,  12.75    ],
        [ 19.921875,  15.9375  ,  15.140625]],

       ...,

       [[ 23.109375, 105.984375,  75.703125],
        [ 21.515625,  88.453125,  68.53125 ],
        [ 21.515625, 1

In [36]:
print(np.min(p1))
print(np.max(p1))

0.0
255.0


In [37]:
np.around(p1).astype(np.uint8)

array([[[  5,  57,  80],
        [  2,  44,  92],
        [  3,  47,  87],
        ...,
        [108,  67,  57],
        [ 12,   2,   6],
        [ 25,  18,  30]],

       [[  3,  37,  75],
        [  4,  45,  73],
        [  7,  42,  76],
        ...,
        [ 91,  67,  69],
        [ 26,   8,  10],
        [ 23,  25,  16]],

       [[  5,  55,  84],
        [  6,  38,  74],
        [  1,  57,  88],
        ...,
        [104,  57,  83],
        [ 26,  17,  13],
        [ 20,  16,  15]],

       ...,

       [[ 23, 106,  76],
        [ 22,  88,  69],
        [ 22, 101,  87],
        ...,
        [138,  88,  51],
        [124,  90,  52],
        [128,  86,  55]],

       [[ 18,  95,  79],
        [ 14, 108,  73],
        [ 23, 103,  87],
        ...,
        [108,  88,  49],
        [118,  86,  60],
        [136,  68,  53]],

       [[ 24, 122,  63],
        [ 20, 117,  80],
        [ 27, 126,  62],
        ...,
        [124,  68,  61],
        [114,  76,  57],
        [128,  63,  50]]